spring:
  application:
    name: strawberry

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/strawberry_db
    username: strawberry_user
    password: strawberry_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq.punlicvm.com
    port: 5672
    password: 12345678
    username: admin
